f = open("example2.txt","w")
f.write("Welcome To csiplearninghub.com")
f.close()
f = open("example2.txt","r")
d = f.read()
print(f.tell())
f.seek(2)
print(f.tell())
d1 = f.read(5)
print(f.tell())
print(d)
print(d1)
